// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: interceptor/grpc/errors/errorx.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Domain is for grouping reasons
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Error is optional, if passed in, it will append to error message
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Reason is the key to get error message template
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Args is the replacer for error message template
	Args []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interceptor_grpc_errors_errorx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interceptor_grpc_errors_errorx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_interceptor_grpc_errors_errorx_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_interceptor_grpc_errors_errorx_proto protoreflect.FileDescriptor

var file_interceptor_grpc_errors_errorx_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x72, 0x72, 0x70, 0x62, 0x22, 0x65, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x67, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x61, 0x6c, 0x61, 0x78, 0x79, 0x2d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interceptor_grpc_errors_errorx_proto_rawDescOnce sync.Once
	file_interceptor_grpc_errors_errorx_proto_rawDescData = file_interceptor_grpc_errors_errorx_proto_rawDesc
)

func file_interceptor_grpc_errors_errorx_proto_rawDescGZIP() []byte {
	file_interceptor_grpc_errors_errorx_proto_rawDescOnce.Do(func() {
		file_interceptor_grpc_errors_errorx_proto_rawDescData = protoimpl.X.CompressGZIP(file_interceptor_grpc_errors_errorx_proto_rawDescData)
	})
	return file_interceptor_grpc_errors_errorx_proto_rawDescData
}

var file_interceptor_grpc_errors_errorx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_interceptor_grpc_errors_errorx_proto_goTypes = []any{
	(*ErrorInfo)(nil), // 0: errpb.ErrorInfo
}
var file_interceptor_grpc_errors_errorx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interceptor_grpc_errors_errorx_proto_init() }
func file_interceptor_grpc_errors_errorx_proto_init() {
	if File_interceptor_grpc_errors_errorx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interceptor_grpc_errors_errorx_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interceptor_grpc_errors_errorx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interceptor_grpc_errors_errorx_proto_goTypes,
		DependencyIndexes: file_interceptor_grpc_errors_errorx_proto_depIdxs,
		MessageInfos:      file_interceptor_grpc_errors_errorx_proto_msgTypes,
	}.Build()
	File_interceptor_grpc_errors_errorx_proto = out.File
	file_interceptor_grpc_errors_errorx_proto_rawDesc = nil
	file_interceptor_grpc_errors_errorx_proto_goTypes = nil
	file_interceptor_grpc_errors_errorx_proto_depIdxs = nil
}
