name: Build check

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/ggsrc/*
      GITHUB_ACCESS_TOKEN: ${{ secrets.CICD_DOCKER_BUILD_PAT }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:14.5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: my-secret
          POSTGRES_DB: user_test_db

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true
          cache: true
          cache-dependency-path: "**/*.sum"
      - run: git config --global url.https://$GITHUB_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: git submodule update --init --recursive
      - run: make build
      - run: make test